#ifndef __CONFIG_HEADER__
#define __CONFIG_HEADER__

#define ENABLE_LEUART0 1
#define ENABLE_USART0  1

#define USART0_LOCATION (USART_ROUTE_LOCATION_LOC4)

#define LEUART0_ENABLE_RX 1
#define LEUART0_ENABLE_TX 1
#define LEUART0_LOCATION (LEUART_ROUTE_LOCATION_LOC3)

#endif
