#ifndef __CONFIG_HEADER__
#define __CONFIG_HEADER__

#define LEUART0_LOCATION (LEUART_ROUTE_LOCATION_LOC3)
#define LEUART0_ENABLE_RX 1
#define LEUART0_ENABLE_TX 1

#define ENABLE_LEUART0 1
#define ENABLE_USART0  1

#endif
