#include "mcu.h"

void init_clocks(void){
    // Start LF 32768Hz RC oscillator
    CMU->OSCENCMD = CMU_OSCENCMD_LFRCOEN;
    while(!(CMU->STATUS & CMU_STATUS_LFRCORDY)){ } // WAIT

    // Start HF 21MHZ RC oscillator
    CMU->OSCENCMD = CMU_OSCENCMD_HFRCOEN;
    while(!(CMU->STATUS & CMU_STATUS_HFRCORDY)){ } // WAIT

    // Set HFRCO freq 21 MHz, and use calibration
    CMU->HFRCOCTRL = (4 << 8) | (DEVINFO->HFRCOCAL1 & 0xff << 0);

    // Set core clock to 21MHz / 2
    CMU->HFCORECLKDIV = CMU_HFCORECLKDIV_HFCORECLKLEDIV_DIV4;

    // Enable peripheral clocks(21MHz / 4, enable GPIO and ADC0).
    CMU->HFPERCLKDIV = CMU_HFPERCLKDIV_HFPERCLKEN | CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK512;
    CMU->HFPERCLKEN0 = CMU_HFPERCLKEN0_GPIO | CMU_HFPERCLKEN0_ADC0 | CMU_HFPERCLKEN0_USART0;

    // Enable RTC
    CMU->LFCLKSEL &= ~_CMU_LFCLKSEL_LFA_MASK;
    CMU->LFCLKSEL |= CMU_LFCLKSEL_LFA_LFRCO;
    CMU->LFACLKEN0 = CMU_LFACLKEN0_RTC;

    // Enable LEUART0
    CMU->LFCLKSEL &= ~_CMU_LFCLKSEL_LFB_MASK;
    CMU->LFCLKSEL |= CMU_LFCLKSEL_LFB_LFRCO;
    CMU->LFBCLKEN0 = CMU_LFBCLKEN0_LEUART0;
}
